### ISSUE TITLE
Module Not showing up

### ISSUE THREAD

**Issue by Nihbor** [VeiledFuryEntertainment/sprawlrunners#2]
Greetings, 
Hate to be a bother, I followed the read me file, and after extracting in the modules data folder, the module is still not showing up within Foundry's modules. 
Any assistance would be appreciated.

**Comment by Tommycore** [comment]
First of all - You're not a bother =)

Second - Does your `Data/modules` directory have a `sprawl-core-rules` folder like in the picture below? Is the `module.json` in said `sprawl-core-rules` folder? Have you updated to the latest Foundry and Swade version?

![image](https://user-images.githubusercontent.com/19580006/157866877-e30c763e-943e-47af-9fbf-9aa905444d01.png)

**Comment by Nihbor** [comment]
![73732a12b6cb3021a9e13fb5dcfc715d](https://user-images.githubusercontent.com/101403252/157867694-d75f0fb4-0ed6-40e5-a829-76b69d9d6c64.png)
This is what I have.. What did I do wrong for extracting?

**Comment by Tommycore** [comment]
The highlighted folder should be named `sprawl-core-rules`. Just rename it and try again.

**Comment by Nihbor** [comment]
Bamm, that did it. Where did I miss renaming it?
Thanks chummer

**Comment by Tommycore** [comment]
Front page, `Installation on Foundry`, list point 2: "There should be a sprawl-core-rules folder in the modules folder...". But you're not the first one to run into the exact same issue, so I'd blame the instructions for being not clear enough ^^

Glad we could figure out your problem. Happy gaming =)
